import { GENERATOR_NAME } from "../constants.js";
import { ensureFinalNewline, formatList } from "../utils.js";

export function renderClaudeInstructions(config, configPath) {
  return ensureFinalNewline(`@AGENTS.md

# Claude Code Adapter

Generated from \`${configPath}\`. Use project subagents from \`.claude/agents/\` for specialist work and skills from \`.claude/skills/\` for lifecycle phases. Keep cross-tool rules in \`AGENTS.md\`; this file contains only Claude Code routing.
`);
}

export function renderCopilotInstructions(config, configPath) {
  const roles = config.roles
    .filter((role) => role.enabled)
    .map((role) => `- \`${role.id}\`: ${role.mission}`)
    .join("\n");
  return ensureFinalNewline(`# ${config.project.name} AI-native Instructions

Generated from \`${configPath}\` by ${GENERATOR_NAME}.

- Treat \`${configPath}\` as the single source of truth for roles, phases, baselines, and artifact paths.
- Read \`${config.paths.baseline}/\` before planning and update seed artifacts under \`${config.paths.artifacts}/\` with evidence.
- Select a custom agent from \`.github/agents/\` when a task has a clear specialist owner.
- Follow the configured phase order and do not pass a gate without stating evidence.
- Preserve unrelated project files and existing user changes.
- Run the relevant repository checks before declaring completion.

## Available roles

${roles}
`);
}

export function renderCopilotAgent(config, role, configPath) {
  return ensureFinalNewline(`---
name: ${yamlString(role.name)}
description: ${yamlString(role.mission)}
---

You are the **${role.name}** specialist for ${config.project.name}.

Read \`${configPath}\`, \`${config.paths.baseline}/\`, and \`${config.paths.roles}/${role.id}.md\` before acting. Own only the responsibilities and deliverables assigned to \`${role.id}\`. State assumptions, keep work traceable to upstream artifacts, verify the active phase gate, and return a concise handoff with evidence and risks.

## Responsibilities

${formatList(role.responsibilities)}
`);
}

export function renderClaudeAgent(config, role, configPath) {
  return ensureFinalNewline(`---
name: ${role.id}
description: ${yamlString(role.mission)}
---

You are the **${role.name}** specialist for ${config.project.name}.

Read \`${configPath}\`, the applicable baselines, and \`${config.paths.roles}/${role.id}.md\`. Work only within the delegated scope. Keep decisions traceable to inputs, update the declared artifact, verify the phase gate, and return evidence, risks, and a handoff summary.

## Responsibilities

${formatList(role.responsibilities)}
`);
}

export function renderCodexAgent(config, role, configPath) {
  const instructions = `You are the ${role.name} specialist for ${config.project.name}. Read ${configPath}, the applicable baselines under ${config.paths.baseline}, and ${config.paths.roles}/${role.id}.md before acting. Work only within delegated scope. Keep decisions traceable to upstream artifacts, verify the phase gate, and return evidence, risks, and a concise handoff. Responsibilities: ${role.responsibilities.join("; ")}`;
  return ensureFinalNewline(`# Generated by ${GENERATOR_NAME} from ${configPath} (schemaVersion 1).
name = ${tomlString(role.id)}
description = ${tomlString(role.mission)}
developer_instructions = ${tomlString(instructions)}
`);
}

function yamlString(value) {
  return JSON.stringify(value);
}

function tomlString(value) {
  return JSON.stringify(value);
}
