import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";

import { AppError } from "../src/domain/errors.ts";
import { validateReleaseEvidence } from "../src/services/release-evidence-validator.ts";

// Isolation tier: A — generated by an independent agent from AC-WF-006 and the
// exported validator contract, before reading the implementation or git diff.

test("AC-WF-006/Tier A: a complete, bound release runbook passes the semantic gate", () => {
  assert.doesNotThrow(() => validateReleaseEvidence({
    artifacts: [{
      artifactKey: "release-runbook",
      content: `<!-- ai-sdlc:release-evidence-v1 -->\n${completeRunbook()}`,
    }],
  }));
});

test("AC-WF-006/Tier A: trusted Run and selected-input bindings are exact and stale-safe", () => {
  const runId = "550e8400-e29b-41d4-a716-446655440000";
  const contentHash = sha256("implementation notes + provenance + test report");
  const expectedInputs = [
    {
      artifactKey: "implementation-notes",
      filePath: "docs/ai-native/engineering/implementation-notes.md",
      contentHash,
    },
    {
      artifactKey: "engineering-provenance",
      filePath: "docs/ai-native/engineering/pr-provenance.md",
      contentHash,
    },
    {
      artifactKey: "test-report",
      filePath: "docs/ai-native/testing/test-report.md",
      contentHash,
    },
  ];
  assert.doesNotThrow(() => validateReleaseEvidence({
    artifacts: [{ artifactKey: "release-runbook", content: completeRunbook() }],
    expectedRunId: runId,
    expectedInputs,
  }));
  assert.doesNotThrow(() => validateReleaseEvidence({
    artifacts: [{
      artifactKey: "release-runbook",
      content: completeRunbook().replace(
        "approved `CC-2026-0825` revision 4",
        "approved `docs/ai-native/product/550e8400-e29b-41d4-a716-446655440000-change-contract.md` revision 4",
      ),
    }],
    expectedRunId: runId,
    expectedInputs,
  }));
  assert.throws(() => validateReleaseEvidence({
    artifacts: [{ artifactKey: "release-runbook", content: completeRunbook() }],
    expectedRunId: "650e8400-e29b-41d4-a716-446655440000",
    expectedInputs,
  }), AppError);
  assert.throws(() => validateReleaseEvidence({
    artifacts: [{ artifactKey: "release-runbook", content: completeRunbook() }],
    expectedRunId: runId,
    expectedInputs: expectedInputs.map((input, index) => (
      index === 0 ? { ...input, contentHash: "f".repeat(64) } : input
    )),
  }), AppError);
  const exactBinding = `| implementation-notes | docs/ai-native/engineering/implementation-notes.md | sha256:${contentHash} |`;
  assertInvalidWithTrustedContext(
    completeRunbook().replace(
      exactBinding,
      `| implementation-notes | attacker/docs/ai-native/engineering/implementation-notes.md.stale | sha256:${contentHash} |`,
    ),
    runId,
    expectedInputs,
  );
  assertInvalidWithTrustedContext(
    completeRunbook().replace(
      exactBinding,
      `| implementation-notes | docs/ai-native/engineering/implementation-notes.md | sha256:aa${contentHash}bb |`,
    ),
    runId,
    expectedInputs,
  );
});

test("AC-WF-006/Tier A: unresolved TODO evidence fails closed", () => {
  assertInvalid(`${completeRunbook()}\n\n- TODO: confirm the production namespace.\n`);
});

test("AC-WF-006/Tier A: every monitoring row needs threshold, window, owner, and action", async (context) => {
  for (const missing of ["threshold", "window", "owner", "action"] as const) {
    await context.test(`missing ${missing}`, () => {
      assertInvalid(completeRunbook({ missingMonitoringField: missing }));
    });
  }
});

test("AC-WF-006/Tier A: rollback evidence fails closed when a critical field is absent", async (context) => {
  for (const missing of [
    "trigger",
    "target",
    "steps",
    "owner",
    "timeObjective",
    "recoveryCheck",
  ] as const) {
    await context.test(`missing ${missing}`, () => {
      assertInvalid(completeRunbook({ missingRollbackField: missing }));
    });
  }
});

test("AC-WF-006/Tier A: an agent cannot forge deployment or release authority", () => {
  assertInvalid(completeRunbook({
    deploymentExecution: "Production deployment approved and completed by the DevOps agent.",
  }));
  const humanOwner = "- **Human release owner:** Human: Release Manager, release-manager@example.com";
  for (const forgedOwner of [
    "Release Manager, release-manager@example.com",
    "Human: Codex",
    "Human: GPT-5",
    "Human: OpenAI assistant",
    "Human: 智能体发布负责人",
  ]) {
    assertInvalid(completeRunbook().replace(
      humanOwner,
      `- **Human release owner:** ${forgedOwner}`,
    ));
  }
  for (const forgedClaim of [
    "Deployment completed by Codex; final release approved.",
    "Codex 已完成生产部署；最终发布已批准。",
    "Production rollout is complete and the release is live.",
    "The release went live successfully.",
  ]) {
    assertInvalid(`${completeRunbook()}\n${forgedClaim}\n`);
  }
  assertInvalid(completeRunbook().replace(
    "- **Rollback decision owner:** Human: Release Manager",
    "- **Rollback decision owner:** Codex",
  ));
  assertInvalid(completeRunbook().replace(
    "- **Go/no-go owner and decision record location:** Human: Release Manager; `release-decisions/CC-2026-0825`",
    "- **Go/no-go owner and decision record location:** ChatGPT",
  ));
  assertInvalid(`${completeRunbook()}\n- **Final release decision owner:** OpenAI assistant\n`);
  for (const [currentOwner, forgedOwner] of [
    ["| Human: On-call SRE | Pause rollout", "| ChatGPT | Pause rollout"],
    ["| Human: Incident Commander | `#incident-checkout`", "| OpenAI assistant | `#incident-checkout`"],
    ["| Architecture NFR-07 | Human: On-call SRE |", "| Architecture NFR-07 | GPT-5 |"],
  ]) {
    assertInvalid(completeRunbook().replace(currentOwner, forgedOwner));
  }
  for (const forgedFutureAuthority of [
    "Codex will deploy the bound artifact and decide final go/no-go.",
    "Codex is the deployment and release decision owner.",
    "The DevOps agent shall execute production rollout after this review.",
    "智能体将负责生产部署并决定最终发布。",
  ]) {
    assertInvalid(`${completeRunbook()}\n${forgedFutureAuthority}\n`);
  }
});

test("AC-WF-006/Tier A: a release artifact without an immutable digest binding is rejected", () => {
  assertInvalid(completeRunbook({ artifactDigest: "not bound to this release artifact" }));
});

type MonitoringField = "threshold" | "window" | "owner" | "action";
type RollbackField = "trigger" | "target" | "steps" | "owner" | "timeObjective" | "recoveryCheck";

function completeRunbook(options: {
  artifactDigest?: string;
  deploymentExecution?: string;
  missingMonitoringField?: MonitoringField;
  missingRollbackField?: RollbackField;
} = {}): string {
  const sourceRevision = "9f76c2b5a1e844c79d24b5f07d2339837ff1a2de";
  const releaseDigest = options.artifactDigest ?? `sha256:${sha256("checkout-service-2026.08.25.tgz")}`;
  const evidenceDigest = sha256("implementation notes + provenance + test report");
  const monitoring = {
    threshold: "HTTP 5xx rate > 1%",
    window: "for 5 consecutive minutes",
    owner: "Human: On-call SRE",
    action: "Pause rollout, page Release Manager, and start rollback assessment",
  };
  if (options.missingMonitoringField) monitoring[options.missingMonitoringField] = "";

  const rollback = {
    trigger: "Smoke check failure or HTTP 5xx threshold breach",
    target: "registry.example.invalid/checkout@sha256:2e5d4f0a3ad428a348bbad1a92cdf7b00805de65d2248b63f57eb792cc9d39d2",
    steps: "Stop rollout; redeploy the bound prior digest; restore traffic; retain evidence",
    owner: "Human: Release Manager",
    timeObjective: "Decision within 10 minutes; recovery within 20 minutes",
    recoveryCheck: "Health endpoint is 200 and 5xx rate stays below 1% for 10 minutes",
  };
  if (options.missingRollbackField) rollback[options.missingRollbackField] = "";

  return [
    "# Release Runbook — checkout-service 2026.08.25",
    "",
    "## Status and immutable bindings",
    "",
    "- **Release readiness:** Ready for human go/no-go",
    "- **Run / Change Contract:** Run `550e8400-e29b-41d4-a716-446655440000`; approved `CC-2026-0825` revision 4",
    "- **Release scope:** Checkout API canary for the approved coupon change only; bounded by `CC-2026-0825`",
    "- **Target environment:** production / checkout-api / cn-east-1",
    `- **Source/product revision:** git commit \`${sourceRevision}\``,
    `- **Implementation Notes:** \`docs/ai-native/engineering/implementation-notes.md\`; approved revision; sha256:${evidenceDigest}`,
    `- **Engineering Provenance:** \`docs/ai-native/engineering/pr-provenance.md\`; approved revision; sha256:${evidenceDigest}`,
    `- **Test Report:** \`docs/ai-native/testing/test-report.md\`; Verification approved and passed; sha256:${evidenceDigest}`,
    "- **Release artifact:** `dist/checkout-service-2026.08.25.tgz` from the approved build",
    `- **Artifact digest:** \`${releaseDigest}\` bound to \`dist/checkout-service-2026.08.25.tgz\``,
    "- **Human release owner:** Human: Release Manager, release-manager@example.com",
    "- **Prepared at / by:** 2026-08-25T09:30:00Z / DevOps preparation execution `exec-4815`",
    `- **Deployment execution:** ${options.deploymentExecution ?? "Not executed by preparing this runbook."}`,
    "",
    "## Trusted upstream input bindings",
    "",
    "| Artifact ID | Current artifact path | Content hash |",
    "| --- | --- | --- |",
    `| implementation-notes | docs/ai-native/engineering/implementation-notes.md | sha256:${evidenceDigest} |`,
    `| engineering-provenance | docs/ai-native/engineering/pr-provenance.md | sha256:${evidenceDigest} |`,
    `| test-report | docs/ai-native/testing/test-report.md | sha256:${evidenceDigest} |`,
    "",
    "## Evidence and supply-chain applicability",
    "",
    "| Evidence | Revision, digest, or durable reference | Applicability and conclusion | Blocker / owner / next action |",
    "| --- | --- | --- | --- |",
    `| CI build and tests | \`ci://build/4815\`; sha256:${evidenceDigest} | Passed for the bound revision | None; CI owner retains the record |`,
    `| Dependency and vulnerability scan | \`ci://scan/4815\`; sha256:${evidenceDigest} | Passed; no accepted critical finding | None; Security reviewer retains the record |`,
    `| SBOM and provenance attestation | \`dist/checkout-service.spdx.json\`; sha256:${evidenceDigest} | Applicable and present | None; Build owner retains the record |`,
    "",
    "## Release preconditions",
    "",
    "| ID | Required state or approval | Evidence / safe reference | Owner | Status | Release impact |",
    "| --- | --- | --- | --- | --- | --- |",
    `| PRE-01 | Verification is approved for the bound source revision | \`test-report.md\`; sha256:${evidenceDigest} | Human: Tester | Satisfied | Blocks release if stale |`,
    `| PRE-02 | Artifact digest matches the candidate in the registry | \`${releaseDigest}\` | Human: Release Manager | Satisfied | Blocks release if mismatched |`,
    "| PRE-03 | Change window and on-call coverage are confirmed | `change-window/2026-08-25` | Human: Release Manager | Satisfied | Blocks operator execution if absent |",
    "",
    "## Ordered rollout",
    "",
    "| Order | Authorized owner | Exact action or reviewed command and trusted context | Expected result | Verification and retained evidence | Stop / continue condition |",
    "| --- | --- | --- | --- | --- | --- |",
    "| Step 1 | Human: Release Manager | Verify bindings and record go/no-go | Durable human decision exists | Signed decision record | Stop without an explicit go decision |",
    "| Step 2 | Human: Deployment operator | Deploy bound digest to 5% canary | Candidate serves canary traffic | Deployment event with digest | Stop on deployment or admission error |",
    "| Step 3 | Human: On-call SRE | Run health and smoke checks | All checks pass | Timestamped check output | Stop on any failed check |",
    "| Step 4 | Human: Deployment operator | Increase traffic to 25%, 50%, then 100% | Bound candidate serves intended traffic | Traffic-shift events | Stop on monitoring threshold breach |",
    "",
    "## Health and smoke checks",
    "",
    "| Check ID | Target / journey | Method and trusted context | Expected result | Owner | Evidence to retain | Result during authorized execution |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    "| HEALTH-01 | Service health | `GET /healthz` through the approved probe | HTTP 200 from every canary instance | Human: On-call SRE | Timestamped probe report | Not run during preparation |",
    "| HEALTH-02 | Checkout coupon journey | Approved synthetic coupon checkout | HTTP 201 and correct total | Human: Tester | Synthetic transaction report | Not run during preparation |",
    "| HEALTH-03 | Revision identity | `GET /version` through the approved probe | Returns the bound source and artifact digest | Human: Deployment operator | Version response record | Not run during preparation |",
    "",
    "## Monitoring and response",
    "",
    "| Signal / NFR or risk ID | Threshold | Observation window | Dashboard/query reference | Owner | Action on breach |",
    "| --- | --- | --- | --- | --- | --- |",
    `| HTTP 5xx rate | ${monitoring.threshold} | ${monitoring.window} | Operations dashboard \`OPS-4815\` | ${monitoring.owner} | ${monitoring.action} |`,
    "| Checkout p95 latency | p95 greater than 450 ms | for 10 consecutive minutes | Operations dashboard `OPS-4815` | Human: On-call SRE | Hold traffic increase and investigate |",
    "",
    "## Rollback and recovery",
    "",
    `- **Rollback decision owner:** ${rollback.owner}`,
    `- **Target recovery time (RTO):** ${rollback.timeObjective}`,
    `- **Rollback triggers:** ${rollback.trigger}`,
    "- **Data/schema/config compatibility:** No schema change; configuration is backward-compatible per ADR-024",
    "- **Backup/restore prerequisites:** Not applicable because the scoped change writes no persistent data; `CC-2026-0825` is the evidence",
    `- **Expected recovered state:** ${rollback.target}`,
    "",
    "| Order | Authorized owner | Recovery action or reviewed command | Expected result | Recovery verification | Status / limitation |",
    "| --- | --- | --- | --- | --- | --- |",
    `| Step 1 | ${rollback.owner} | ${rollback.steps} | ${rollback.target} | ${rollback.recoveryCheck} | Reviewed plan; not executed during preparation |`,
    "",
    "## Incident and escalation",
    "",
    "| Trigger / severity | Immediate response and rollout state | Incident/release owner reference | Escalation and communication path | Evidence to retain |",
    "| --- | --- | --- | --- | --- |",
    "| Customer checkout unavailable / SEV-1 | Stop rollout and declare incident | Human: Incident Commander | `#incident-checkout` and paging | Events, decisions, logs, and timestamps |",
    "| Data-integrity signal / SEV-1 | Freeze rollout and preserve evidence | Human: Security and data owner | Security paging | Queries, decisions, logs, and timestamps |",
    "",
    "## Risks, exceptions, and open decisions",
    "",
    "| ID | Known defect, untested item, risk, or decision | Evidence | Human owner | Durable acceptance / due condition | Release impact |",
    "| --- | --- | --- | --- | --- | --- |",
    "| RISK-01 | Cache warm-up may briefly increase latency | Architecture NFR-07 | Human: On-call SRE | Hold each rollout step until the 10-minute latency window passes | Residual monitored risk |",
    "| DECISION-01 | Final production go/no-go | This bound runbook | Human: Release Manager | Record explicit decision before operator action | Blocks execution while open |",
    "",
    "## Human go/no-go and execution boundary",
    "",
    "- **Runbook conclusion:** Ready for human go/no-go",
    "- **Unresolved blockers:** None before this readiness handoff",
    "- **Go/no-go owner and decision record location:** Human: Release Manager; `release-decisions/CC-2026-0825`",
    "- **Required revalidation triggers:** Any Run, source, artifact, digest, environment, test, risk, or plan change",
    "",
    "Preparing this runbook does not approve or perform deployment, rollout, rollback, production migration, production smoke testing, CI changes, secret changes, publication, risk acceptance, or incident command.",
    "",
  ].join("\n");
}

function assertInvalid(content: string): void {
  assert.throws(
    () => validateReleaseEvidence({
      artifacts: [{ artifactKey: "release-runbook", content }],
    }),
    (error: unknown) => {
      assert.ok(error instanceof AppError);
      assert.match(error.message, /release|runbook|evidence|发布|证据/iu);
      return true;
    },
  );
}

function assertInvalidWithTrustedContext(
  content: string,
  expectedRunId: string,
  expectedInputs: ReadonlyArray<{
    artifactKey: string;
    filePath: string;
    contentHash: string;
  }>,
): void {
  assert.throws(
    () => validateReleaseEvidence({
      artifacts: [{ artifactKey: "release-runbook", content }],
      expectedRunId,
      expectedInputs,
    }),
    AppError,
  );
}

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}
